export const UPDATE_APPOINTMENT_REQUEST = "UPDATE_APPOINTMENT_REQUEST";
export const UPDATE_APPOINTMENT_FAILED = "UPDATE_APPOINTMENT_FAILED";
export const UPDATE_APPOINTMENT_SUCCESS = "UPDATE_APPOINTMENTSUCCESST";
export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST";
export const DELETE_APPOINTMENT_FAILED = "DELETE_APPOINTMENT_FAILED";
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENTSUCCESST";