export const GET_ALL_MOTIFS = 'GET_ALL_MOTIFS';
export const GET_ALL_MOTIFS_SUCCESS = 'GET_ALL_MOTIFS_SUCCESS';
export const GET_ALL_MOTIFS_FAILED = 'GET_ALL_MOTIFS_FAILED';

export const POST_MOTIF_REQUEST = 'POST_MOTIF_REQUEST';
export const POST_MOTIF_REQUEST_SUCCESS = 'POST_MOTIF_REQUEST_SUCCESS';
export const POST_MOTIF_REQUEST_FAILED = 'POST_MOTIF_REQUEST_FAILED';
