export const GET_ALL_SPECIALITIES = 'GET_ALL_SPECIALITIES';
export const GET_ALL_SPECIALITIES_SUCCESS = 'GET_ALL_SPECIALITIES_SUCCESS';

export const POST_SPEC_REQUEST = 'POST_SPEC_REQUEST';
export const POST_SPEC_REQUEST_SUCCESS = 'POST_SPEC_REQUEST_SUCCESS';
export const POST_SPEC_REQUEST_FAILED = 'POST_SPEC_REQUEST_FAILED';
