export const GET_ALL_PRATICIENS_REQUEST = 'GET_ALL_PRATICIENS_REQUEST';
export const GET_ALL_PRATICIENS_SUCCESS = 'GET_ALL_PRATICIENS_SUCCESS';
export const GET_ALL_PRATICIENS_FAILED = 'GET_ALL_PRATICIENS_FAILED';
