export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const RESET_ALL_FIELD = 'RESET_ALL_FIELD';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

export const POST_USER_REQUEST = 'POST_USER_REQUEST';
export const POST_USER_REQUEST_SUCCESS = 'POST_USER_REQUEST_SUCCESS';
export const POST_USER_REQUEST_FAILED = 'POST_USER_REQUEST_FAILED';
